### ISSUE TITLE
Merge Dependabot PRs

### ISSUE THREAD

**Issue by jayp0521** [ignlg/heap-js#616]
If the Dependabot PRs could be auto merged, that would be great!

https://github.com/marketplace/actions/dependabot-auto-merge

Awesome implementation of Heap!

**Comment by ignlg** [comment]
Hello @jayp0521 , thanks for reaching out.

Indeed, I will get rid of `dependabot` because Heap.js has no dependencies, just development ones (typedoc, rollup, and such), and all dependabot's PRs just add noise. If it had dependencies, your comment would be a great addition, I totally agree.

I am glad that you like the implementation! I just want to keep it simple and easy to use and hack :)

Thanks!
